language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10
      compiler: clang
      env:
        - COMPILER="clang++" SANITIZE=false

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test
  - make install